package model;
// Generated 2017-04-22 17:07:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PomiarGniazdko generated by hbm2java
 */
public class PomiarGniazdko  implements java.io.Serializable {


     private int pomiarId;
     private int sprzetId;
     private Date momentPomiaru;
     private BigDecimal pomiarNapiecie;
     private BigDecimal pomiarPrad;
     private BigDecimal pomiarMoc;

    public PomiarGniazdko() {
    }

	
    public PomiarGniazdko(int pomiarId, int sprzetId) {
        this.pomiarId = pomiarId;
        this.sprzetId = sprzetId;
    }
    public PomiarGniazdko(int pomiarId, int sprzetId, Date momentPomiaru, BigDecimal pomiarNapiecie, BigDecimal pomiarPrad, BigDecimal pomiarMoc) {
       this.pomiarId = pomiarId;
       this.sprzetId = sprzetId;
       this.momentPomiaru = momentPomiaru;
       this.pomiarNapiecie = pomiarNapiecie;
       this.pomiarPrad = pomiarPrad;
       this.pomiarMoc = pomiarMoc;
    }
    
    public PomiarGniazdko(int pomiarId, int sprzetId, BigDecimal pomiarNapiecie, BigDecimal pomiarPrad, BigDecimal pomiarMoc) {
       this.pomiarId = pomiarId;
       this.sprzetId = sprzetId;
       this.momentPomiaru = new Date();
       this.pomiarNapiecie = pomiarNapiecie;
       this.pomiarPrad = pomiarPrad;
       this.pomiarMoc = pomiarMoc;
    }
   
    public int getPomiarId() {
        return this.pomiarId;
    }
    
    public void setPomiarId(int pomiarId) {
        this.pomiarId = pomiarId;
    }
    public int getSprzetId() {
        return this.sprzetId;
    }
    
    public void setSprzetId(int sprzetId) {
        this.sprzetId = sprzetId;
    }
    public Date getMomentPomiaru() {
        return this.momentPomiaru;
    }
    
    public void setMomentPomiaru(Date momentPomiaru) {
        this.momentPomiaru = momentPomiaru;
    }
    public BigDecimal getPomiarNapiecie() {
        return this.pomiarNapiecie;
    }
    
    public void setPomiarNapiecie(BigDecimal pomiarNapiecie) {
        this.pomiarNapiecie = pomiarNapiecie;
    }
    public BigDecimal getPomiarPrad() {
        return this.pomiarPrad;
    }
    
    public void setPomiarPrad(BigDecimal pomiarPrad) {
        this.pomiarPrad = pomiarPrad;
    }
    public BigDecimal getPomiarMoc() {
        return this.pomiarMoc;
    }
    
    public void setPomiarMoc(BigDecimal pomiarMoc) {
        this.pomiarMoc = pomiarMoc;
    }

    @Override
    public String toString() {
        return "PomiarGniazdko{" + "pomiarId=" + pomiarId + ", sprzetId=" + sprzetId + ", momentPomiaru=" + momentPomiaru + ",/n pomiarNapiecie=" + pomiarNapiecie + ", pomiarPrad=" + pomiarPrad + ", pomiarMoc=" + pomiarMoc + '}';
    }




}


