package model;
// Generated 2017-04-22 17:07:11 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Sprzet generated by hbm2java
 */
public class Sprzet implements java.io.Serializable {

    private int sprzetId;
    private String opis;
    private String typ;
    private Integer czyWlaczony;

    public Sprzet() {
    }

    public Sprzet(int sprzetId, String typ) {
        this.sprzetId = sprzetId;
        this.typ = typ;
    }

    public Sprzet(int sprzetId, String opis, String typ, Integer czyWlaczony) {
        this.sprzetId = sprzetId;
        this.opis = opis;
        this.typ = typ;
        this.czyWlaczony = czyWlaczony;
    }

    public int getSprzetId() {
        return this.sprzetId;
    }

    public void setSprzetId(int sprzetId) {
        this.sprzetId = sprzetId;
    }

    public String getOpis() {
        return this.opis;
    }

    public void setOpis(String opis) {
        this.opis = opis;
    }

    public String getTyp() {
        return this.typ;
    }

    public void setTyp(String typ) {
        this.typ = typ;
    }

    public Integer getCzyWlaczony() {
        return this.czyWlaczony;
    }

    public void setCzyWlaczony(Integer czyWlaczony) {
        this.czyWlaczony = czyWlaczony;
    }

    public static BigDecimal findLastPomiar(List<PomiarTemperatura> pomiary, Sprzet s) {
        BigDecimal wynik = new BigDecimal(0.0);
        Date date = null;
        for (PomiarTemperatura pomiar : pomiary) {
            if (pomiar.getSprzetId() == s.getSprzetId()) {
                if (date == null || date.before(pomiar.getMomentPomiaru())) {
                    wynik = pomiar.getPomiarTemp();
                    date = pomiar.getMomentPomiaru();
                }
            }
        }
        return wynik;
    }

}
